services:

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: portfolio-backend
#     ports:
#       - "8000:8000"


# volumes:
#   postgres_data: